### PR TITLE
feat(i18n): add Japanese translations

### PR DESCRIPTION
**Pull request by akodate**
### Summary

Adding Japanese language support.

### Other Information

I made a few changes so I've created a new pull request.

### CODE REVIEW

**Comment by raiseandfall** [comment]
@akodate Thanks for the contribution! We will review your changes and merge it soon.

**Comment by akodate** [comment]
@raiseandfall Any updates? I'd love to translate the Blockcerts app if you can show me where to do that.

**Comment by raiseandfall** [comment]
@akodate we're currently reviewing your PR, I'll give you an update very soon. You're more than welcome to translate the Blockcerts app! I'm not in charge of those two, but I believe you can learn more at https://github.com/blockchain-certificates/wallet-iOS and https://github.com/blockchain-certificates/wallet-android.

Thank you!

**Pull request merged**
