### PR TITLE
Retrieve issuer profile for V3 certificates

### PR DESCRIPTION
**Pull request by lemoustachiste**
### BREAKING CHANGE

V3 certificates only reference a URI for the `issuer` property as per VC specs: https://www.w3.org/TR/vc-data-model/#issuer, so we need to preload the issuer profile from the specified URI at instantiation time. 
That means now that the process of instantiating a `Certificate` object becomes async, and consumers need to update their code with the following:
```
const certificate = new Certificate(definition);
await certificate.init();
```

We also fix the distant revocation list lookup. The code was always assuming it was available locally. The 2 things are intertwined and it became impossible to do this fix for V3 without preloading the issuer profile (otherwise we would try and access a property of a string).

I would like to hear opinions on whether we should do the same for V1 and V2 certificates too. At this moment in V3 we set the issuer to be a string url, but it can be an object (as per the specs); that would then make it more similar to V1 and V2 in behavior. So that could mean:

1. we either make Blockcerts V3 use an object always (and that we actually remove the need for a breaking change now). The behavior is similar as currently. This would mean reverting some of the changes of this PR, but nothing absurd. The main downside is blocking the V3 spec on something not iso with the VC spec.
2. we allow more flexibility and closer respect to the VC spec, which means we keep this PR, but to improve the verification process and have more similarities between all versions we also preload the issuer profile for V1 and V2 (keeping in mind that local `revocationList` has precedence over distant one as per https://github.com/blockchain-certificates/cert-schema/blob/master/docs/issuer_schema-2.1.md#revocationlist). It can be a bit complicated and really could just be a nice to have.
3. we keep this PR and maintain V1 and V2 as they currently are handled (fetching issuerProfile in the verification steps). This incurs less work but also means that consumers have to update their code to consume the new version of the package.

Left to do:
- [x] ~~Follow VC spec more precisely and handle case when the `issuer` property is an object.~~ Actually handled already
- [x] in case of V3 verification steps (in cases of options 2 and 3), remove `getIssuerProfile` from pre-programmed steps
- [x] update README (in case we discard option 1)

### CODE REVIEW

**Comment by AnthonyRonning** [comment]
> we either make Blockcerts V3 use an object always

I wouldn't want to impose this requirement unless we had to. Perhaps we treat it like we should have been treating issuer profiles to begin with - we fill in the values for our issuer profile if they exist in an issuer object, and fill the gaps with the distant issuer profile? 

My personal opinion is to always treat the remote as the source of truth instead of the certificate, when related to issuer profiles. What if the issuer name changes? Or the revocation list gets hosted somewhere else? I understand the V2 spec says to use the cert as the source of truth for issuer profile info if it's there, but I don't know if I would agree with that now. There's pros and cons to both. 


> preload the issuer profile for V1 and V2

Is this a requirement for being able to pull in the issuer profile revocation list if the revocation list doesn't exist in the certificate? If the "breaking change" is something only for V3, is it really a breaking change? If we go back and change V1 & V2 initialization, it would be breaking but if this is just a V3 requirement then current consumers don't have to change, right?

**Comment by lemoustachiste** [comment]
> What if the issuer name changes? Or the revocation list gets hosted somewhere else? I understand the V2 spec says to use the cert as the source of truth for issuer profile info if it's there, but I don't know if I would agree with that now. There's pros and cons to both.

I think I agree with you, but I lack context as to why it was decided this way.

> If the "breaking change" is something only for V3, is it really a breaking change? If we go back and change V1 & V2 initialization, it would be breaking but if this is just a V3 requirement then current consumers don't have to change, right? 

It is a breaking change in the sense that to move forward with CVJS (and use version 4 thus), one needs to go async.
The thing is, there is only one entry point to CVJS, which is the `Certificate` constructor. I believe this should remain as such because you shouldn't need to decide this piece of logic before consuming the code. Potentially, the Constructor could also call the `parseJSON` method, but then you'd have to programmatically decide whether the certificate was successfully instantiated (V1, V2) or not (V3), and this goes back to having to my previous point.

My inclination is to go with option 3 at this moment, and maybe integrate option 2 if we realize this could improve the verification process (after all, if the certificate is malformed it will fail early).

**Comment by AnthonyRonning** [comment]
Cool yeah I agree, sounds good.

**Comment by guix77** [comment]
> My personal opinion is to always treat the remote as the source of truth instead of the certificate, when related to issuer profiles. What if the issuer name changes? Or the revocation list gets hosted somewhere else? I understand the V2 spec says to use the cert as the source of truth for issuer profile info if it's there, but I don't know if I would agree with that now. There's pros and cons to both.

I also agree with this.

Maybe it was decided in the beginning to also include the issuer data in the certificate to allow some display tasks without any external call, but I definitively would have preferred to do all in external calls. For verification the ultimate source of truth is always external and not having this local data would have lead to smaller size certificates. Anyways.

I'm a bit lost with the options in this PR, I would say choose the most optimal for the future that also keeps the v1 and v2 working. For the v2 revocation I'll talk about it also in https://github.com/blockchain-certificates/cert-verifier-js/issues/308#issuecomment-610423109 but I can still add the revocation list in my certificates.

**Comment by lemoustachiste** [comment]
Isn't the idea behind using the link in the local certs sort of the same that drives JSONLD soft requirement for caching the contexts? I can see 2 things there:
- the revocation list is part of the certs, and as such cannot be tampered with without failing the cert
- the revocation list call will less likely return hacked data/be intercepted?

**Pull request merged**
