### PR TITLE
Added Italian language translations

### PR DESCRIPTION
**Pull request by dariomas**

### CODE REVIEW

**Comment by dariomas** [comment]
How to set ${NPM_TOKEN} in order to let Travis build correctly?

**Comment by lemoustachiste** [comment]
@dariomas for security reasons Travis restricts PRs from forks to have access to ENV variables. The correct approach here is to make a PR repo to repo. 

What you could do is add this repo to your remotes, and push to a new branch, so that you can open the PR and it can be tested

**Comment by dariomas** [comment]
> @dariomas for security reasons Travis restricts PRs from forks to have access to ENV variables. The correct approach here is to make a PR repo to repo.
> 
> What you could do is add this repo to your remotes, and push to a new branch, so that you can open the PR and it can be tested

Hi @lemoustachiste ,
I do not have the access rights permission to push to a new branch to this remote repository; I can only do PR from my own repository, as I have done.

Please let me know if I'm wrong.

**Comment by lemoustachiste** [comment]
ok

let me handle that for you. I'll do this before the end of the day.

**Comment by lemoustachiste** [comment]
overwritten by https://github.com/blockchain-certificates/cert-verifier-js/pull/117
@dariomas

**Pull request closed without merging**
