### PR TITLE
Use regex match for merkle root comparison

### PR DESCRIPTION
**Pull request by unlimit**
fixes issue #26

### CODE REVIEW

**Comment by raiseandfall** [comment]
@unlimit Thanks for the contribution! Can you add some tests here to cover that change? https://github.com/blockchain-certificates/cert-verifier-js/blob/master/tests/testChecks.js

**Comment by unlimit** [comment]
@raiseandfall done!

**Comment by AnthonyRonning** [comment]
Hey @unlimit, thanks for adding the test. 

One thing I would like to see, if it's okay, is a test on a sample certificate. We don't have any cases for us to test out smart contract transactions, and our cert-issuer doesn't currently issue these types of transactions. I'd want to make sure your certificate and any others sent to smart contracts verify with any refactoring coming up in the near future.

**Comment by unlimit** [comment]
@AnthonyRonning yes, here is our [sample certificate](https://s3.amazonaws.com/rocketx-development/test-cert.json).
And [Ethereum TX](
https://ropsten.etherscan.io/tx/0x5baa42fe321704bab6b73a8fbacca61a09fd007183fc5e0283ecb3bd5a80d4be) for it

**Comment by lemoustachiste** [comment]
@unlimit I think what @AnthonyRonning meant was that he would like to have a test covering your use case (something a bit larger than a unit test), so that we could have confidence we would not break your case when refactoring (which we are doing since we are already working on the v2).

**Comment by unlimit** [comment]
@lemoustachiste thank you for the details. Honestly I don't see any sense in larger test covering. (It is very simple change and unit test should completely cover it)
Merkle root comparison is a question(not an issue) to Blockcerts protocol(specially to v2):
1. Should it be strict?
 In this case, js and python verifier must use the same rules. Also issuer will not be able to issue certificate via ethereum smart contract methods.
2. Should it be soft?
This can be very handy, but maybe you have some reasons to block this? Any security concerns?

**Comment by AnthonyRonning** [comment]
Yes, @lemoustachiste, thanks for clarifying, that's what I meant. 

@unlimit, I'm asking for the benefit of both of us here, not necessarily for the code change involved. Thank for for providing that unit test, and I agree it should cover it.

Our lm-cert-issuer open source does not issue to smart contracts, so we do not have any coverage for this use case. It would be nice to have it, but I guess since our open source doesn't provide this functionality, we shouldn't worry about covering others' specific implementations of blockcerts? Thoughts @kimdhamilton?

**Comment by raiseandfall** [comment]
Digging down in old opened PRs, what should we do here @AnthonyRonning @kimdhamilton ?

**Comment by lemoustachiste** [comment]
closing as this has been open forever with no action from op

**Pull request closed without merging**
